# Generated by Django 6.0.3 on 2026-03-27 11:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederatedModelUpdate',
            fields=[
                ('update_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255)),
                ('model_version', models.CharField(max_length=50)),
                ('gradient_hash', models.CharField(max_length=255)),
                ('update_size_kb', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('aggregated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'federated_model_updates',
            },
        ),
    ]
