# Generated by Django 6.0.4 on 2026-04-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('consultation', 'Consultation'), ('verification', 'Verification'), ('payment', 'Payment'), ('system', 'System'), ('reminder', 'Reminder'), ('prescription', 'Prescription'), ('medical_record', 'Medical Record'), ('medication_reminder', 'Medication Reminder')], max_length=20),
        ),
    ]
