# Generated by Django 6.0.4 on 2026-04-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('in-person', 'In-Person'), ('lab_test', 'Lab Test'), ('home_treatment', 'Home Treatment')], default='virtual', max_length=20),
        ),
    ]
