import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:dio/dio.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/services/auth_service.dart';
import '../../../../core/constants/api_constants.dart';

/// Read-only view of the AI's sectioned summary of a finished call.
///
/// This is NOT the manual report template — it's a narrative summary of what
/// was said, generated by Groq right after the call. The doctor reads it (and
/// can copy it) as a reference while writing the official record.
class AiCallSummaryScreen extends StatefulWidget {
  final String consultationId;
  final String? patientName;
  final String? initialSummary;

  const AiCallSummaryScreen({
    super.key,
    required this.consultationId,
    this.patientName,
    this.initialSummary,
  });

  @override
  State<AiCallSummaryScreen> createState() => _AiCallSummaryScreenState();
}

class _AiCallSummaryScreenState extends State<AiCallSummaryScreen> {
  bool _loading = false;
  String? _error;
  String _summary = '';

  @override
  void initState() {
    super.initState();
    final initial = (widget.initialSummary ?? '').trim();
    if (initial.isNotEmpty) {
      _summary = initial;
    } else {
      _fetch();
    }
  }

  Future<void> _fetch() async {
    setState(() {
      _loading = true;
      _error = null;
    });
    try {
      final token = await AuthService.getAccessToken();
      final res = await Dio().get(
        '${ApiConstants.baseUrl}${ApiConstants.consultations}${widget.consultationId}/ai-summary/',
        options: Options(headers: {'Authorization': 'Bearer $token'}),
      );
      final data = res.data is Map ? res.data as Map : const {};
      _summary = (data['summary'] ?? '').toString().trim();
    } catch (_) {
      _error = 'Could not load the AI summary.';
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  /// Split the markdown into (heading, body) sections on "## " lines.
  List<_Section> _parse(String md) {
    final sections = <_Section>[];
    String? title;
    final body = <String>[];
    void flush() {
      if (title != null || body.isNotEmpty) {
        sections.add(_Section(title ?? 'Summary', body.join('\n').trim()));
      }
    }

    for (final raw in md.split('\n')) {
      final line = raw.trimRight();
      if (line.startsWith('## ')) {
        flush();
        title = line.substring(3).replaceAll('#', '').trim();
        body.clear();
      } else if (line.startsWith('# ')) {
        // Treat a single-# heading as a section title too.
        flush();
        title = line.substring(2).trim();
        body.clear();
      } else {
        body.add(line);
      }
    }
    flush();
    // If the model didn't use headings at all, show the whole thing as one card.
    if (sections.isEmpty && md.trim().isNotEmpty) {
      sections.add(_Section('Summary', md.trim()));
    }
    return sections;
  }

  String _clean(String s) => s.replaceAll('**', '').replaceAll('__', '');

  @override
  Widget build(BuildContext context) {
    final sections = _parse(_summary);
    return Scaffold(
      backgroundColor: const Color(0xFFF5F7FA),
      appBar: AppBar(
        title: const Text(
          'AI call summary',
          style: TextStyle(fontFamily: 'Inter', fontWeight: FontWeight.w800),
        ),
        backgroundColor: Colors.white,
        foregroundColor: AppColors.darkBlue900,
        elevation: 0.5,
        actions: [
          if (_summary.trim().isNotEmpty)
            IconButton(
              tooltip: 'Copy summary',
              icon: const Icon(Icons.copy_rounded, size: 20),
              onPressed: () {
                Clipboard.setData(ClipboardData(text: _summary));
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(content: Text('Summary copied')),
                );
              },
            ),
        ],
      ),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : _error != null
              ? _ErrorView(text: _error!, onRetry: _fetch)
              : sections.isEmpty
                  ? const _ErrorView(
                      text:
                          'No summary is available yet for this consultation.')
                  : ListView(
                      padding: const EdgeInsets.fromLTRB(16, 16, 16, 32),
                      children: [
                        _Banner(patientName: widget.patientName),
                        const SizedBox(height: 14),
                        for (final s in sections) ...[
                          _SectionCard(
                            title: _clean(s.title),
                            lines: s.body
                                .split('\n')
                                .map((l) => l.trim())
                                .where((l) => l.isNotEmpty)
                                .map(_clean)
                                .toList(),
                          ),
                          const SizedBox(height: 12),
                        ],
                      ],
                    ),
    );
  }
}

class _Section {
  final String title;
  final String body;
  _Section(this.title, this.body);
}

class _Banner extends StatelessWidget {
  final String? patientName;
  const _Banner({this.patientName});

  @override
  Widget build(BuildContext context) {
    final who = (patientName ?? '').trim();
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: AppColors.darkBlue500.withOpacity(0.10),
        borderRadius: BorderRadius.circular(14),
      ),
      child: Row(
        children: [
          const Icon(Icons.auto_awesome_rounded,
              color: AppColors.darkBlue500, size: 22),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  who.isEmpty ? 'AI-generated summary' : 'Summary · $who',
                  style: const TextStyle(
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w800,
                    fontSize: 14,
                    color: AppColors.darkBlue900,
                  ),
                ),
                const SizedBox(height: 2),
                const Text(
                  'A summary of what was discussed — not your official report.',
                  style: TextStyle(
                    fontFamily: 'Inter',
                    fontSize: 12,
                    color: AppColors.grey500,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _SectionCard extends StatelessWidget {
  final String title;
  final List<String> lines;
  const _SectionCard({required this.title, required this.lines});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFFE6EAF0)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              fontSize: 14.5,
              color: AppColors.darkBlue900,
            ),
          ),
          const SizedBox(height: 8),
          for (final line in lines) _bodyLine(line),
        ],
      ),
    );
  }

  Widget _bodyLine(String line) {
    final isBullet = line.startsWith('- ') || line.startsWith('* ') || line.startsWith('•');
    final text = isBullet ? line.replaceFirst(RegExp(r'^[-*•]\s*'), '') : line;
    return Padding(
      padding: const EdgeInsets.only(bottom: 6),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          if (isBullet)
            const Padding(
              padding: EdgeInsets.only(top: 6, right: 8),
              child: Icon(Icons.circle, size: 5, color: AppColors.grey500),
            ),
          Expanded(
            child: Text(
              text,
              style: const TextStyle(
                fontFamily: 'Inter',
                fontSize: 13.5,
                height: 1.45,
                color: Color(0xFF374151),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _ErrorView extends StatelessWidget {
  final String text;
  final VoidCallback? onRetry;
  const _ErrorView({required this.text, this.onRetry});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.auto_awesome_outlined,
                size: 56, color: AppColors.grey500.withOpacity(0.5)),
            const SizedBox(height: 16),
            Text(
              text,
              textAlign: TextAlign.center,
              style: const TextStyle(
                fontFamily: 'Inter',
                color: AppColors.grey500,
                fontSize: 14,
                height: 1.4,
              ),
            ),
            if (onRetry != null) ...[
              const SizedBox(height: 16),
              TextButton(onPressed: onRetry, child: const Text('Retry')),
            ],
          ],
        ),
      ),
    );
  }
}
