# Generated by Django 4.2.13 on 2026-04-12 18:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcareprovider',
            name='specialization',
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='other_specialty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='specialty',
            field=models.CharField(choices=[('generalist', 'Generalist'), ('nurse', 'Nurse'), ('midwife', 'Midwife'), ('other', 'Other')], default='generalist', max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcareprovider',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthcareprovider',
            name='years_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProviderSchedule',
            fields=[
                ('schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_working', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='providers.healthcareprovider')),
            ],
            options={
                'db_table': 'provider_schedules',
                'unique_together': {('provider', 'day')},
            },
        ),
    ]
