# Generated by Django 4.2.13 on 2026-04-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_providerreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercredential',
            name='document_type',
            field=models.CharField(choices=[('national_id_front', 'National ID Front'), ('national_id_back', 'National ID Back'), ('medical_license', 'Medical License')], max_length=20),
        ),
        migrations.AlterField(
            model_name='providercredential',
            name='document_url',
            field=models.URLField(max_length=1024),
        ),
    ]
