# Generated by Django 6.0.3 on 2026-03-27 11:03

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISymptomSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms_input', models.TextField()),
                ('parsed_symptoms', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('triage_score', models.IntegerField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('escalated_to_provider', models.BooleanField(default=False)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='patients.patient')),
            ],
            options={
                'db_table': 'ai_symptom_sessions',
            },
        ),
    ]
