# Generated by Django 4.2.13 on 2026-04-12 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisymptomsession',
            name='escalated_to_provider',
        ),
        migrations.RemoveField(
            model_name='aisymptomsession',
            name='model_version',
        ),
        migrations.RemoveField(
            model_name='aisymptomsession',
            name='parsed_symptoms',
        ),
        migrations.AddField(
            model_name='aisymptomsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aisymptomsession',
            name='suggested_specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aisymptomsession',
            name='symptoms_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_engine.aisymptomsession')),
            ],
            options={
                'db_table': 'ai_chat_messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
