# Generated by Django 4.2.13 on 2026-04-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_remove_aisymptomsession_escalated_to_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='image',
            field=models.TextField(blank=True, help_text='Base64 encoded image or image URL', null=True),
        ),
    ]
