# Generated by Django 6.0.4 on 2026-04-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_medicalrecord_extras_referral'),
        ('providers', '0006_drop_specialty_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_prescriptions', to='providers.healthcareprovider'),
        ),
    ]
