# Generated by Django 6.0.4 on 2026-04-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_prescription_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='audio_gs_uri',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='consultation',
            name='call_transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_ai_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
