# Generated by Django 6.0.4 on 2026-04-20 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Blood', 'Blood'), ('Urine', 'Urine'), ('Imaging', 'Imaging'), ('STD', 'STD'), ('Other', 'Other')], max_length=50)),
                ('price', models.IntegerField(help_text='Price in XAF')),
                ('turnaround', models.CharField(help_text='e.g. 24h, 30 min', max_length=50)),
                ('sample_type', models.CharField(help_text='e.g. Blood (venous), Mid-stream urine', max_length=100)),
                ('fasting_required', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
