# Generated by Django 4.2.13 on 2026-04-12 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_remove_healthcareprovider_specialization_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('residence', 'Residence'), ('clinic', 'Clinic')], default='residence', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='providers.healthcareprovider'),
        ),
    ]
