# Generated by Django 4.2.13 on 2026-04-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_fee', models.IntegerField(default=15000)),
                ('service_charge', models.IntegerField(default=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'platform_settings',
            },
        ),
        migrations.AlterModelTable(
            name='providersubscription',
            table=None,
        ),
    ]
