# Generated by Django 6.0.4 on 2026-04-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_external_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pending_booking',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
