# Generated by Django 6.0.4 on 2026-04-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('prescription', 'Prescription'), ('medical_record', 'Medical Record'), ('referral', 'Referral')], default='text', max_length=20),
        ),
    ]
